version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cop_db
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - cop-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: cop_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    networks:
      - cop-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: cop-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cop_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - cop-network

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    container_name: cop-worker
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/cop_mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - cop-network

  frontend:
    build:
      context: ./Cop-Frontend-Angular
      dockerfile: Dockerfile
    container_name: cop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cop-network

  dashboard:
    build:
      context: ./DashBoard-COP
      dockerfile: Dockerfile
    container_name: cop-dashboard
    ports:
      - "4200:80"
    depends_on:
      - backend
      - worker
    networks:
      - cop-network

networks:
  cop-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data: